#ifndef __WUNIT_BLUETOOTH_UUIDS__
#define __WUNIT_BLUETOOTH_UUIDS__

#define CONTROL_SERVICE_UUID "66ec8a63-a0d5-44a7-97f7-0dba5c956458"
#define DATA_SERVICE_UUID "a13ee111-076e-49eb-be32-a87331ff152d"

//  Control service characteristics
#define PASSKEY_CHARACTERISTIC_UUID "0257e7a5-0e01-4fbf-8288-e48675d6abb3"
// #define STARTER_CHARACTERISTIC_UUID ""
// #define LEFT_TURN_CHARASTERISTIC_UUID ""
// #define RIGHT_TURN_CHARACTERISTIC_UUID ""
// #define HORN_CHARACTERISTIC_UUID ""
// #define BRAKE_CHARACTERISTIC_UUID ""
// #define LIGHT_CHARACTERISTIC_UUID ""
// #define HIGHT_BEAM_CHARACTERISTIC_UUID ""
// #define IGNITION_CHARACTERISTIC_UUID ""
// #define MARKERS_CHARACTERISTIC_UUID ""
// #define AUX_1_CHARACTERISTIC_UUID ""
// #define AUX_2_CHARACTERISTIC_UUID ""

#endif