#ifndef __DEFAULT_VARIABLES_H__
#define __DEFAULT_VARIABLES_H__

#define DEFAULT_ANGLE_COMPENSATE 0

#define DEFAULT_BLUETOOTH_PASSKEY 123456

#define DEFAULT_KILL_ON_FALL true

#define DEFAULT_BLINKERS_SPEED 667

#define DEFAULT_SPEEDO_UPDATE_INTERVAL 0.5
#define DEFAULT_TACHO_UPDATE_INTERVAL 0.5

#endif